version: '3.8'

services:
  storeapi:
    build:
      context: ../../StoreAPI/StoreAPI
      dockerfile: ../../DevOps/Docker/Dockerfile.storeapi
    container_name: storeapi
    ports:
      - 5000:5000
    networks:
      - storenetwork
    depends_on:
      - storedb

  storedb:
    build:
      context: .
      dockerfile: Dockerfile.storedb
    container_name: storedb
    ports:
      - 1433:1433
    networks:
      - storenetwork
    volumes:
      - /var/opt/mssql:/var/opt/mssql
    environment:
      - SA_PASSWORD=your_password # set your password here

networks:
  storenetwork:
    name: storenetwork
    driver: bridge
