apiVersion: v1
kind: PersistentVolume
metadata:
    name: storedb-pv
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    gcePersistentDisk:
        pdName: storeapi-mssql-persistent
        fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: storedb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
